models:
 - name : hello
   config:
      access: public
 - name : dim_customers
   config:
     contract:
      enforced: true
      columns:
       - name: id1
         data_type: int
       - name: id2
         data_type: int